# Generated by Django 4.1.2 on 2022-11-17 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_messagesendhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesendhistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 11, 17, 16, 8, 17, 50328, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
