# Generated by Django 4.1.2 on 2024-02-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_emailadd_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesendhistory',
            name='topic',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
